###
GET http://localhost:3000

###
GET http://localhost:3000/partners

###
POST http://localhost:3000/partners
Content-Type: application/json

{
    "name": "Partner 2"
}

###
@partner_id = 03c20c6b-a7a0-4fdf-ae4d-1d78f49f2190

###
GET http://localhost:3000/customers

###
POST http://localhost:3000/customers
Content-Type: application/json

{
    "name": "Customer 1",
    "cpf": "592.110.870-74"
}

###
@customer_id = e86f7efb-a885-488b-9b66-00e5e448677e

###
GET http://localhost:3000/events

###
POST http://localhost:3000/events
Content-Type: application/json

{
    "name": "Event 1",
    "description": "Description 1",
    "date": "2020-01-01T00:00:00.000Z",
    "partner_id": "{{partner_id}}"
}

###
@event_id = 97c4b200-d333-49af-bf89-8700ef9efc57

###
GET http://localhost:3000/events/{{event_id}}/sections

###
POST http://localhost:3000/events/{{event_id}}/sections
Content-Type: application/json

{
    "name": "Section 1",
    "description": "Description 1",
    "total_spots": 1,
    "price": 200
}

###
PUT http://localhost:3000/events/{{event_id}}/publish-all

###
@section_id = 95ee1798-9ebb-4a03-a08a-945a6ce6ec66

###
PUT http://localhost:3000/events/{{event_id}}/sections/{{section_id}}
Content-Type: application/json

{
    "name": "Section 1 updateddddd",
    "description": "Description 1 updatedddd"
}

###
GET http://localhost:3000/events/{{event_id}}/sections/{{section_id}}/spots

###
@spot_id = 28712f81-e0a1-4fb7-87ff-9ac4177979ce

###
PUT http://localhost:3000/events/{{event_id}}/sections/{{section_id}}/spots/{{spot_id}}
Content-Type: application/json

{
    "location": "Location 1 updateddddqqqq"
}

###
GET http://localhost:3000/events/{{event_id}}/orders

###
POST http://localhost:3000/events/{{event_id}}/orders
Content-Type: application/json

{
    "customer_id": "{{customer_id}}",
    "section_id": "{{section_id}}",
    "spot_id": "{{spot_id}}",
    "card_token": "tok_visa"
}